//! Simple rewrite of the prism autoloader plugin,
//! to load the desired language definition for syntax
//! highlighting at compile time.
//! https://github.com/PrismJS/prism/blob/master/plugins/autoloader/prism-autoloader.js

use lazy_static::lazy_static;
use std::{
    collections::{HashMap, HashSet},
    iter,
};

/// Builds an HashMap from a json-like structure.
macro_rules! hashmap {
	($value:literal) => {{
		vec![$value]
	}};

	([$($value:literal),+]) => {{
		vec![$($value),+]
	}};

    ($($key:literal : $val:tt),+) => {{
		let mut hash_map = HashMap::new();
		$(hash_map.insert($key, hashmap![$val]);)+
		hash_map
    }};
}

/// Bundles in the Knots binary all prism languages.
macro_rules! include_prism_languages {
	($($lang: literal),*) => {{
		let mut hash_map = HashMap::new();
		$(hash_map.insert($lang, include_str!(concat!("../js/prism/prism-", $lang, ".min.js")));)+
		hash_map
	}};
}

lazy_static! {
    static ref LANGS: HashMap<&'static str, &'static str> = include_prism_languages!(
        "abap",
        "abnf",
        "actionscript",
        "ada",
        "agda",
        "al",
        "antlr4",
        "apacheconf",
        "apex",
        "apl",
        "applescript",
        "aql",
        "arduino",
        "arff",
        "asciidoc",
        "asm6502",
        "aspnet",
        "autohotkey",
        "autoit",
        "bash",
        "basic",
        "batch",
        "bbcode",
        "birb",
        "bison",
        "bnf",
        "brainfuck",
        "brightscript",
        "bro",
        "bsl",
        "c",
        "cfscript",
        "chaiscript",
        "cil",
        "clike",
        "clojure",
        "cmake",
        "coffeescript",
        "concurnas",
        "cpp",
        "crystal",
        "csharp",
        "csp",
        "css-extras",
        "css",
        "cypher",
        "d",
        "dart",
        "dataweave",
        "dax",
        "dhall",
        "diff",
        "django",
        "dns-zone-file",
        "docker",
        "dot",
        "ebnf",
        "editorconfig",
        "eiffel",
        "ejs",
        "elixir",
        "elm",
        "erb",
        "erlang",
        "etlua",
        "excel-formula",
        "factor",
        "firestore-security-rules",
        "flow",
        "fortran",
        "fsharp",
        "ftl",
        "gcode",
        "gdscript",
        "gedcom",
        "gherkin",
        "git",
        "glsl",
        "gml",
        "go",
        "graphql",
        "groovy",
        "haml",
        "handlebars",
        "haskell",
        "haxe",
        "hcl",
        "hlsl",
        "hpkp",
        "hsts",
        "http",
        "ichigojam",
        "icon",
        "idris",
        "iecst",
        "ignore",
        "inform7",
        "ini",
        "io",
        "j",
        "java",
        "javadoc",
        "javadoclike",
        "javascript",
        "javastacktrace",
        "jolie",
        "jq",
        "js-extras",
        "js-templates",
        "jsdoc",
        "json",
        "json5",
        "jsonp",
        "jsstacktrace",
        "jsx",
        "julia",
        "keyman",
        "kotlin",
        "kumir",
        "latex",
        "latte",
        "less",
        "lilypond",
        "liquid",
        "lisp",
        "livescript",
        "llvm",
        "lolcode",
        "lua",
        "makefile",
        "markdown",
        "markup-templating",
        "markup",
        "matlab",
        "mel",
        "mizar",
        "mongodb",
        "monkey",
        "moonscript",
        "n1ql",
        "n4js",
        "nand2tetris-hdl",
        "naniscript",
        "nasm",
        "neon",
        "nginx",
        "nim",
        "nix",
        "nsis",
        "objectivec",
        "ocaml",
        "opencl",
        "oz",
        "parigp",
        "parser",
        "pascal",
        "pascaligo",
        "pcaxis",
        "peoplecode",
        "perl",
        "php-extras",
        "php",
        "phpdoc",
        "plsql",
        "powerquery",
        "powershell",
        "processing",
        "prolog",
        "promql",
        "properties",
        "protobuf",
        "psl",
        "pug",
        "puppet",
        "pure",
        "purebasic",
        "purescript",
        "python",
        "q",
        "qml",
        "qore",
        "r",
        "racket",
        "reason",
        "regex",
        "renpy",
        "rest",
        "rip",
        "roboconf",
        "robotframework",
        "ruby",
        "rust",
        "sas",
        "sass",
        "scala",
        "scheme",
        "scss",
        "shell-session",
        "smali",
        "smalltalk",
        "smarty",
        "sml",
        "solidity",
        "solution-file",
        "soy",
        "sparql",
        "splunk-spl",
        "sqf",
        "sql",
        "squirrel",
        "stan",
        "stylus",
        "swift",
        "t4-cs",
        "t4-templating",
        "t4-vb",
        "tap",
        "tcl",
        "textile",
        "toml",
        "tsx",
        "tt2",
        "turtle",
        "twig",
        "typescript",
        "typoscript",
        "unrealscript",
        "uri",
        "v",
        "vala",
        "vbnet",
        "velocity",
        "verilog",
        "vhdl",
        "vim",
        "visual-basic",
        "warpscript",
        "wasm",
        "wiki",
        "xeora",
        "xml-doc",
        "xojo",
        "xquery",
        "yaml",
        "yang",
        "zig"
    );
    static ref LANG_DEPENDENCIES: HashMap<&'static str, Vec<&'static str>> = hashmap! {
        "javascript": "clike",
        "actionscript": "javascript",
        "apex": [
            "clike",
            "sql"
        ],
        "arduino": "cpp",
        "aspnet": [
            "markup",
            "csharp"
        ],
        "birb": "clike",
        "bison": "c",
        "c": "clike",
        "csharp": "clike",
        "cpp": "c",
        "cfscript": "clike",
        "chaiscript": [
            "clike",
            "cpp"
        ],
        "coffeescript": "javascript",
        "crystal": "ruby",
        "css-extras": "css",
        "d": "clike",
        "dart": "clike",
        "django": "markup-templating",
        "ejs": [
            "javascript",
            "markup-templating"
        ],
        "etlua": [
            "lua",
            "markup-templating"
        ],
        "erb": [
            "ruby",
            "markup-templating"
        ],
        "fsharp": "clike",
        "firestore-security-rules": "clike",
        "flow": "javascript",
        "ftl": "markup-templating",
        "gml": "clike",
        "glsl": "c",
        "go": "clike",
        "groovy": "clike",
        "haml": "ruby",
        "handlebars": "markup-templating",
        "haxe": "clike",
        "hlsl": "c",
        "idris": "haskell",
        "java": "clike",
        "javadoc": [
            "markup",
            "java",
            "javadoclike"
        ],
        "jolie": "clike",
        "jsdoc": [
            "javascript",
            "javadoclike",
            "typescript"
        ],
        "js-extras": "javascript",
        "json5": "json",
        "jsonp": "json",
        "js-templates": "javascript",
        "kotlin": "clike",
        "latte": [
            "clike",
            "markup-templating",
            "php"
        ],
        "less": "css",
        "lilypond": "scheme",
        "markdown": "markup",
        "markup-templating": "markup",
        "mongodb": "javascript",
        "n4js": "javascript",
        "nginx": "clike",
        "objectivec": "c",
        "opencl": "c",
        "parser": "markup",
        "php": "markup-templating",
        "phpdoc": [
            "php",
            "javadoclike"
        ],
        "php-extras": "php",
        "plsql": "sql",
        "processing": "clike",
        "protobuf": "clike",
        "pug": [
            "markup",
            "javascript"
        ],
        "purebasic": "clike",
        "purescript": "haskell",
        "qml": "javascript",
        "qore": "clike",
        "racket": "scheme",
        "jsx": [
            "markup",
            "javascript"
        ],
        "tsx": [
            "jsx",
            "typescript"
        ],
        "reason": "clike",
        "ruby": "clike",
        "sass": "css",
        "scss": "css",
        "scala": "java",
        "shell-session": "bash",
        "smarty": "markup-templating",
        "solidity": "clike",
        "soy": "markup-templating",
        "sparql": "turtle",
        "sqf": "clike",
        "squirrel": "clike",
        "swift": "clike",
        "t4-cs": [
            "t4-templating",
            "csharp"
        ],
        "t4-vb": [
            "t4-templating",
            "vbnet"
        ],
        "tap": "yaml",
        "tt2": [
            "clike",
            "markup-templating"
        ],
        "textile": "markup",
        "twig": "markup",
        "typescript": "javascript",
        "v": "clike",
        "vala": "clike",
        "vbnet": "basic",
        "velocity": "markup",
        "wiki": "markup",
        "xeora": "markup",
        "xml-doc": "markup",
        "xquery": "markup"
    };
    static ref LANG_ALIASES: HashMap<&'static str, Vec<&'static str>> = hashmap! {
        "html": "markup",
        "xml": "markup",
        "svg": "markup",
        "mathml": "markup",
        "ssml": "markup",
        "atom": "markup",
        "rss": "markup",
        "js": "javascript",
        "g4": "antlr4",
        "adoc": "asciidoc",
        "shell": "bash",
        "shortcode": "bbcode",
        "rbnf": "bnf",
        "oscript": "bsl",
        "cs": "csharp",
        "dotnet": "csharp",
        "cfc": "cfscript",
        "coffee": "coffeescript",
        "conc": "concurnas",
        "jinja2": "django",
        "dns-zone": "dns-zone-file",
        "dockerfile": "docker",
        "gv": "dot",
        "eta": "ejs",
        "xlsx": "excel-formula",
        "xls": "excel-formula",
        "gamemakerlanguage": "gml",
        "hs": "haskell",
        "idr": "idris",
        "gitignore": "ignore",
        "hgignore": "ignore",
        "npmignore": "ignore",
        "webmanifest": "json",
        "kt": "kotlin",
        "kts": "kotlin",
        "kum": "kumir",
        "tex": "latex",
        "context": "latex",
        "ly": "lilypond",
        "emacs": "lisp",
        "elisp": "lisp",
        "emacs-lisp": "lisp",
        "md": "markdown",
        "moon": "moonscript",
        "n4jsd": "n4js",
        "nani": "naniscript",
        "objc": "objectivec",
        "objectpascal": "pascal",
        "px": "pcaxis",
        "pcode": "peoplecode",
        "pq": "powerquery",
        "mscript": "powerquery",
        "pbfasm": "purebasic",
        "purs": "purescript",
        "py": "python",
        "rkt": "racket",
        "rpy": "renpy",
        "robot": "robotframework",
        "rb": "ruby",
        "sh-session": "shell-session",
        "shellsession": "shell-session",
        "smlnj": "sml",
        "sol": "solidity",
        "sln": "solution-file",
        "rq": "sparql",
        "t4": "t4-cs",
        "trig": "turtle",
        "ts": "typescript",
        "tsconfig": "typoscript",
        "uscript": "unrealscript",
        "uc": "unrealscript",
        "url": "uri",
        "vb": "visual-basic",
        "vba": "visual-basic",
        "xeoracube": "xeora",
        "yml": "yaml"
    };
}

/// Retreives the prism plugins needed for these languages
pub fn find_plugins(langs: &[String]) -> Vec<&'static str> {
    let mut already_found = HashSet::new();
    let mut plugins = Vec::new();

    for lang in langs {
        // find the abbreviation if there is one
        let lang = LANG_ALIASES
            .get(lang.as_str())
            .map(|vec| vec[0])
            .unwrap_or(lang);

        // get the dependency plugins and add the main plugin
        plugins.extend(
            LANG_DEPENDENCIES
                .get(lang)
                .cloned()
                .unwrap_or_default()
                .into_iter()
                .chain(iter::once(lang))
                .filter(|&lang_dep| already_found.insert(lang_dep))
                .filter_map(|lang_dep| LANGS.get(lang_dep)),
        );
    }

    plugins
}
