name: ci

defaults:
  run:
    shell: bash

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  # build croco on every OS
  build:
    # let's use a matrix so we can later add more OS
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
      - name: Clone project
        uses: actions/checkout@v2

      - name: Build Knots release
        run: |
          cargo build --release

      - name: Upload Knots [windows]
        uses: actions/upload-artifact@v2
        with:
          name: knots-${{ matrix.os }}
          path: target/release/knots.exe

      - name: Upload Knots [unix]
        uses: actions/upload-artifact@v2
        with:
          name: knots-${{ matrix.os }}
          path: target/release/knots

  # upload the resulting binaries to github releases
  upload:
    needs: build
    runs-on: ubuntu-latest
    steps:
      # retreive the previously saved binaries
      - uses: actions/download-artifact@v2
        with:
          name: knots-windows-latest
          path: windows
      - uses: actions/download-artifact@v2
        with:
          name: knots-ubuntu-latest
          path: linux
      - uses: actions/download-artifact@v2
        with:
          name: knots-macos-latest
          path: macos

      # get the commit hash
      # https://github.community/t/add-short-sha-to-github-context/16418/11
      - name: get commit infos
        id: commit
        run: echo "::set-output name=hash::$(echo ${GITHUB_SHA} | cut -c1-8)"

      - name: create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.commit.outputs.hash }}
          release_name: Release ${{ steps.commit.outputs.hash }}
          body: This is an automated build for commit ${{ steps.commit.outputs.hash }}.
          draft: false
          prerelease: true

      - name: upload Windows binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./windows/knots.exe
          asset_name: knots-${{ steps.commit.outputs.hash }}.exe
          asset_content_type: application/x-msdownload

      - name: upload Linux binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./linux/knots
          asset_name: knots-${{ steps.commit.outputs.hash }}
          asset_content_type: application/x-elf

      - name: upload MacOS binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./macos/knots
          asset_name: knots-${{ steps.commit.outputs.hash }}
          asset_content_type: application/x-elf
